<?php

/**
 * @file
 * GMS Sitename.
 */

/**
 * Implements hook_preprocess_page().
 *
 * @throws \Exception
 */
function gms_sitename_preprocess_page(&$variables) {
  if (isset($variables['site_name']) && !empty($variables['site_name'])) {
    $query = \Drupal::database()->select('gms_sitename_data', 'gs');
    $query->fields('gs', []);
    $results = $query->execute()->fetchAll();
    $rows = [];
    if ($results) {
      foreach ($results as $value) {
        if ($value->check_type == 'url') {
          $rows['url'][$value->condition_type] = $value->sitename;
        }
        else {
          $rows['ctype'][$value->condition_type] = $value->sitename;
        }
      }
    }
    $current_path = \Drupal::service('path.current')->getPath();
    $variables['current_path'] = $current_path;
    if (isset($rows['url'][$current_path])) {
      $variables['site_name'] = $rows['url'][$current_path];
    }
    elseif (isset($variables['node'])) {
      $node = $variables['node'];
      if (isset($rows['ctype'][$node->type])) {
        $variables['site_name'] = $rows['ctype'][$node->type];
      }
    }
  }
}
