<?php

/**
 * @file
 * PDF Exort Module.
 */

/**
 * Implements hook_theme_registry_alter().
 */
function gms_pdflink_theme_registry_alter(&$theme_registry) {
}

/**
 * Implements hook_theme().
 */
function gms_pdflink_theme($existing, $type, $theme, $path) {
  return [
    'entity_print' => [
      'path' => $path . '/templates',
      'template' => 'entity-print',
      'variables' => [
        'title' => '',
        'ochamenu' => NULL,
        'content' => NULL,
        'entity_print_css' => NULL,
      ],
    ],
    'page_print' => [
      'path' => $path . '/templates',
      'template' => 'page-print',
      'variables' => [
        'title' => '',
        'content' => NULL,
        'page_print_css' => '',
      ],
    ],
  ];
}
