display_configuration:
  link_text: 'Seleccionar medios'
widgets:
  552cfb05-063f-47a9-81d1-e1260fc8a402:
    settings:
      submit_text: 'Seleccionar medios'
    label: 'Elegir medio existente'
  7e4422b4-dbe9-40f6-9b74-e2bf31b98ae8:
    label: 'Subir nueva imagen'
