display:
  default:
    display_title: Máster
    display_options:
      exposed_form:
        options:
          submit_button: Aplicar
          reset_button_label: Restablecer
          exposed_sorts_label: 'Ordenar por'
          sort_asc_label: Asc
          sort_desc_label: Desc
      pager:
        options:
          expose:
            items_per_page_label: 'Elementos por página'
            items_per_page_options_all_label: '- Todo -'
            offset_label: Desplazamiento
          tags:
            previous: '‹ anterior'
            next: 'siguiente ›'
            first: '« primero'
            last: 'último »'
      fields:
        title:
          separator: ', '
        created:
          label: 'Creado en'
        status:
          label: Estado
          separator: ', '
        type:
          label: Tipo
      filters:
        title:
          expose:
            label: Título
      sorts:
        created:
          expose:
            label: 'Fecha de autoría'
  entity_browser_1:
    display_title: 'Navegador de entidades'
