_core:
  default_config_hash: R4IF-ClDHXxblLcG0L7MgsLvfBIMAvi_skumNFQwkDc
module:
  acl: 0
  admin_toolbar: 0
  admin_toolbar_tools: 0
  anchor_link: 0
  automated_cron: 0
  big_pipe: 0
  block: 0
  block_class: 0
  block_content: 0
  breakpoint: 0
  ckeditor: 0
  ckeditor_config: 0
  ckeditor_font: 0
  ckeditor_iframe: 0
  codemirror_editor: 0
  colorbutton: 0
  comment: 0
  condition_query: 0
  config: 0
  config_translation: 0
  config_update: 0
  contact: 0
  contact_storage: 0
  content_access: 0
  content_moderation: 0
  contextual: 0
  core_event_dispatcher: 0
  csp: 0
  ctools: 0
  datetime: 0
  dblog: 0
  ds_switch_view_mode: 0
  dynamic_page_cache: 0
  editor: 0
  entity: 0
  entity_browser: 0
  entity_browser_entity_form: 0
  entity_browser_example: 0
  environment_indicator: 0
  fakeobjects: 0
  features: 0
  field: 0
  field_event_dispatcher: 0
  field_ui: 0
  file: 0
  filter: 0
  genpass: 0
  gms_group_migrate: 0
  gms_pdflink: 0
  gms_secure_role: 0
  gms_sitename: 0
  google_tag: 0
  help: 0
  history: 0
  hook_event_dispatcher: 0
  html_export: 0
  image: 0
  imce: 0
  inline_entity_form: 0
  jquery_ui: 0
  language: 0
  layout_discovery: 0
  libraries: 0
  link: 0
  locale: 0
  mailcontrol: 0
  maintenance200: 0
  media: 0
  media_entity_browser: 0
  media_entity_browser_media_library: 0
  media_library: 0
  menu_block: 0
  menu_breadcrumb: 0
  menu_entity_index: 0
  menu_export: 0
  menu_firstchild: 0
  menu_link_attributes: 0
  menu_link_content: 0
  menu_ui: 0
  metatag: 0
  migrate: 0
  migrate_drupal: 0
  migrate_file: 0
  migrate_plus: 0
  migrate_tools: 0
  modules_weight: 0
  mysql: 0
  node: 0
  noreqnewpass: 0
  ocha_snap: 0
  options: 0
  page_cache: 0
  page_specific_class: 0
  panelbutton: 0
  path: 0
  path_alias: 0
  quickedit: 0
  rdf: 0
  redirect: 0
  rest: 0
  scrollup: 0
  search: 0
  semanticviews: 0
  serialization: 0
  shortcut: 0
  social_api: 0
  social_auth: 0
  social_auth_hid: 0
  social_auth_roles: 0
  stage_file_proxy: 0
  superfish: 0
  syslog: 0
  system: 0
  taxonomy: 0
  tb_megamenu: 0
  text: 0
  token: 0
  token_filter: 0
  tome_base: 0
  tome_static: 0
  toolbar: 0
  tour: 0
  update: 0
  user: 0
  user_event_dispatcher: 0
  user_expire: 0
  user_login: 0
  userprotect: 0
  video_embed_field: 0
  views_base_url: 0
  views_block_area: 0
  views_event_dispatcher: 0
  views_ui: 0
  workflows: 0
  ds: 1
  pathauto: 1
  ds_extras: 2
  gms_ocha: 5
  content_translation: 10
  views: 10
  minimal: 1000
theme:
  bartik: 0
  seven: 0
  bootstrap: 0
  dxpr_theme: 0
  stable: 0
  common_design: 0
  gms_ocha_common: 0
profile: minimal
