_core:
  default_config_hash: yOPH6uEZYRHbg2OFP-bze0jGr06fI-Gr_66W-vA8Faw
report-only:
  enable: true
  directives:
    connect-src:
      base: self
      sources:
        - fonts.gstatic.com
        - '*.unocha.org'
    font-src:
      base: self
      sources:
        - fonts.gstatic.com
    img-src:
      base: self
      sources:
        - github.com
    object-src:
      base: none
    script-src:
      base: self
      sources:
        - www.googletagmanager.com
    script-src-elem:
      base: self
      flags:
        - unsafe-inline
    style-src:
      base: self
    style-src-attr:
      base: self
      flags:
        - unsafe-inline
    style-src-elem:
      base: self
    frame-ancestors:
      base: self
  reporting:
    plugin: sitelog
enforce:
  enable: true
  directives:
    object-src:
      base: none
    frame-ancestors:
      base: self
  reporting:
    plugin: sitelog
