features:
  node_user_picture: 1
  comment_user_picture: 1
  comment_user_verification: 1
  favicon: 1
logo:
  use_default: 0
  path: sites/default/files/ocha-logo.svg
favicon:
  use_default: 1
common_design_node_title:
  full: full
  blog_data: 0
  pdf: 0
  revision: 0
  rss: 0
  search_index: 0
  search_result: 0
  teaser: 0
  token: 0
