_core:
  default_config_hash: WKPJoaS0nZiIboNwD58sBSpxmtib3XbeyMWgbExqsnE
url_with_class: "/content/gms-one|onegms-home-pg\r\n/content/cbpf|cbpf-section\r\n/content/cerf|cerf-section\r\n/glossary/*|glossary-pg\r\n/searchpage|search-pg\r\n/content/gms-one|onegms-support-pg"
