_core:
  default_config_hash: yTxtFqBHnEWxQswuWvkjE8mKw2t8oKuCL1q8KnfHuGE
langcode: en
uuid: 8426c366-b035-4eb5-98e1-914c8e753c52
name: 'Grant Management System (GMS) Support / Help Portal'
mail: sagar.ramgade@trigyn.com
slogan: 'CBPF GRANT MANAGEMENT SYSTEM (GMS)'
page:
  403: ''
  404: ''
  front: /node/191
admin_compact_mode: false
weight_select_max: 100
default_langcode: en
mail_notification: ''
