<?php

/**
 * @file
 * GMS Ocha Module.
 */

use Drupal\Core\Ajax\AjaxResponse;
use Drupal\Core\Ajax\HtmlCommand;
use Drupal\Core\Ajax\SettingsCommand;

/**
 * Implements hook_preprocess_page.
 */
function gms_ocha_theme($existing, $type, $theme, $path) {
  return [
    'gms_ocha_welcome' => [
      'variables' => [
        'welcome' => NULL,
        'logoutUrl' => NULL,
        'logged_in' => NULL,
        'name' => NULL
      ]
    ],
    'pooled_fund_sankey_chart' => [
      'render element'  => 'form',
      'variables' => [
        'sankey' => NULL,
        'form_var' => NULL,
      ],
    ],
    'pooled_fund_explore_widget' => [
      'variables' => [],
    ],
    'pooled_fund_widget' => [
      'render element' => 'form',
      'variables' => [
        'donation' => NULL,
        'pooled_fund_form' => NULL,
      ],
    ],
  ];
}

/**
 * Implements Country callback.
 */
function gms_ocha_poolfund_donor_country_callback($form, $form_state) {
  $form_state->setRebuild();
  $sankey_chart = \Drupal::service('renderer')->render($form['sankey_chart']);
  $jsonURL = $form['jsonUrl'];
  $response = new AjaxResponse();
  $settings['drupalSettings'] = ['sankey_chart' => ['path' => ['sankey' => $jsonURL]]];
  $response->addCommand(new SettingsCommand($settings, TRUE));
  $response->addCommand(new HtmlCommand('#pooled-fund-sankey-chart', $sankey_chart, $settings));
  $form['#attached']['library'][] = 'gms_ocha/sankey_chart';
  $response->setAttachments($form['#attached']);
  return $response;
}

/**
 * Implements poolfund callback.
 */
function gms_ocha_poolfund_callback($form, $form_state) {
  $form_state->setRebuild();
  $poolfund_badges = \Drupal::service('renderer')->render($form['poolfund_badges']);
  $response = new AjaxResponse();
  $response->addCommand(new HtmlCommand('#pooled-fund-badges', $poolfund_badges));
  return $response;
}
